include:
- file: helmfile-infra/helmchart-pipeline.gitlab-ci.yml
  project: devops/tools/ci

variables:
  PIPELINE_CUSTOM_JOBS: |-
    lint chart
    package chart
    publish chart

LINT:
  extends: .lint chart job

PACK:
  extends: .package chart job

PUBLISH:
  extends: .publish chart job

deploy environment:
  extends: .trigger helmfile infra project job
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'
    when: never
  - !reference [.trigger helmfile infra project job, rules]
  variables:
    HELMFILE_ENVS: |-
      IKVA_CHART_VERSION=$HELM_CHART_PACKAGE_VERSION
