include:
- file: helmfile-infra/helmchart-pipeline.gitlab-ci.yml
  project: devops/tools/ci

variables:
  PIPELINE_CUSTOM_JOBS: package chart

PACK:
  extends: .package chart job

deploy environment:
  extends: .trigger helmfile infra project job
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'
    when: never
  - !reference [.trigger helmfile infra project job, rules]
  variables:
    HELMFILE_ENVS: |-
      IKVA_CHART_VERSION=$HELM_CHART_PACKAGE_VERSION
