include:
- file: helmfile-infra/helmchart-pipeline.gitlab-ci.yml
  project: devops/tools/ci
  ref: $CI_LIBRARY_REF_NAME

deploy environment:
  variables:
    HELMFILE_ENVS: |-
      IKVA_CHART_VERSION=$HELM_CHART_PACKAGE_VERSION
