include:
- file: service-helmchart-pipeline.gitlab-ci.yml
  project: devops/tools/ci  

lint chart:
  extends: .lint chart job
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'

package chart:
  extends: .package chart job

publish chart:
  extends: .push chart to artifactory job

deploy environment:
  extends: .trigger helmfile infra project job
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'
    when: never
  - !reference [.trigger helmfile infra project job, rules]
  needs:
  - job: publish chart
  variables:
    IKVA_CHART_VERSION: $HELM_CHART_PACKAGE_VERSION
